### ISSUE TITLE
size of the tree

### ISSUE THREAD

**Issue by masanobufukuoka** [bokkypoobah/BokkyPooBahsRedBlackTreeLibrary#8]
is there any way to get the size of the tree?

**Comment by bokkypoobah** [comment]
Sorry, no simple variable that keeps track of the tree size. You can use JavaScript to extract the whole tree - https://github.com/bokkypoobah/BokkyPooBahsRedBlackTreeLibrary/blob/master/test/functions.js#L276-L325

**Comment by bokkypoobah** [comment]
Or add a variable to keep track of the tree size. Closing for now.
